/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.stonewall.swaudioplayer

public class SWAudioPlayer {
    public fun fromLibrary(): String {
        return "From Library"
    }
}
