/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.stonewall.swaudioplayer

import androidx.compose.material3.Text
import androidx.compose.runtime.Composable

@Composable
public fun SWAudioPlayer() {
    Text(
        text = "Hello From Library 3")
}


